for_solve.c File Reference
#include <stdio.h>
#include <math.h>
#include <assert.h>
#include `sq_sol.h`
Enumerations
enum cases {
TOXIC = -100
, INFINITE = 100
, TOXIC = -100
, INFINITE = 100
,
TOXIC = -100
, INFINITE = 100
 }
Functions
void get_input (double *coef, char letter)
Main logic functions.
int check_input (double a_coef, double b_coef, double c_coef)
int square_solve (double a_coef, double b_coef, double c_coef, double *sol1, double *sol2)
Solver for square equations by coefficients.
int linear_solve (double b_coef, double c_coef, double *sol1)
Solver for linear equations by coefficients.
int special_case (double c_coef)
Solver for case of 0-power polynomial.
int compare (double dble)
Additional function.
int compare2 (double dble1, double dble2)
void input (double *a_coef, double *b_coef, double *c_coef)
int Solve (double a_coef, double b_coef, double c_coef, double *sol1, double *sol2)
int output (double sol1, double sol2, int num_roots)
Enumeration Type Documentation
cases
enum cases
Enumerator
TOXIC
INFINITE
TOXIC
INFINITE
TOXIC
INFINITE For errors.
Definition at line 7 of file for_solve.c.
{TOXIC = -100, INFINITE = 100};
Function Documentation
check_input()
int check_input (double a_coef, double b_coef, double c_coef)
compare()
int compare (double dble)
Additional function.
Definition at line 171 of file for_solve.c.
                        {
    assert(isfinite(dble));
    const double EPS = 0.000001;
    return EPS > fabs(dble);
}
References EPS.
Referenced by linear_solve(), Solve(), special_case(), and square_solve().
compare2()
int compare2 (double dble1, double dble2)
Definition at line 178 of file for_solve.c.
                                        {
    assert(isfinite(dble1));
    assert(isfinite(dble2));
    const double EPS = 0.000001;
    return EPS > fabs(dble1 - dble2);
}
References EPS.
Referenced by tester().
get_input()
void get_input (double * coef, char letter)
Main logic functions.
Processing input of one variable.
Parameters
 in *coef Pointer for coefficient cell
 in letter Name of coef that will be printed
Definition at line 38 of file for_solve.c.
                                         {
    printf("%c: ", letter);
    while (!scanf("%lf", coef)){
        printf("Your input has wrong type, please, reenter coefficient %c\n", letter);
        printf("%c: ", letter);
        while(getchar() != '\n') // buffer clean
              ;
        }
}
Referenced by input().
input()
void input (double * a_coef, double * b_coef, double * c_coef)
Definition at line 27 of file for_solve.c.
                                                         {
    printf("Please, enter the coefficients of your equation of the form a*x^2 + b*x + c = 0\n");
    get_input(a_coef, 'a');
    get_input(b_coef, 'b');
    get_input(c_coef, 'c');
}
References get_input().
Referenced by main().
linear_solve()
int linear_solve (double b_coef, double c_coef, double * sol1)
Solver for linear equations by coefficients.
Parameters
 in b_coef,c_coef Value of coefficient a, b, c
 in *sol1 Pointer to the answer's cell
Warning
b_coef != 0 (We assume that equation actually is Linear)
Returns
Number of roots
Definition at line 118 of file for_solve.c.
                                                             {
    assert(isfinite(b_coef));
    assert(isfinite(c_coef));
    assert(!compare(b_coef));
    assert(sol1 != NULL);
    *sol1 = -c_coef/b_coef;
    return 1;
}
References compare().
Referenced by Solve().
output()
int output (double sol1, double sol2, int num_roots)
Definition at line 143 of file for_solve.c.
                                                   {
    assert(isfinite(sol1));
    assert(isfinite(sol2));
    switch (num_roots){
    case 1 : {printf("Your equation has only one root: %g", sol1);
        return 0;}
    case 2 : {printf("Your equation has two roots: \nx1 = %g \nx2 = %g", sol1, sol2);
        return 0;}
    case -1 : {printf("Your equation has complex roots");
            return 1;
        return 1;}
    case 0 : {printf("Your equation has no roots");
        return 0;}
    case INFINITE : {printf("Your equation has INFINITE roots");
        return 0;}
    default : return 2;
    }
}
References INFINITE.
Referenced by main().
Solve()
int Solve (double a_coef, double b_coef, double c_coef, double * sol1, double * sol2)
Definition at line 50 of file for_solve.c.
                                                                                 {
    assert(isfinite(a_coef));
    assert(isfinite(b_coef));
    assert(isfinite(c_coef));
    assert(sol1 != NULL);
    assert(sol2 != NULL);
    assert(sol1 != sol2);
    int num_roots = TOXIC;
    if (compare(a_coef)) {
        if (compare(b_coef)){
            num_roots = special_case(c_coef);
            *sol1 = 0;
            *sol2 = *sol1;
            }
        else
            num_roots = linear_solve(b_coef,c_coef,sol1);
        }
    else
        num_roots = square_solve(a_coef, b_coef, c_coef, sol1, sol2);
    return num_roots;
}
References compare(), linear_solve(), special_case(), square_solve(), and TOXIC.
Referenced by main(), and tester().
special_case()
int special_case (double c_coef)
Solver for case of 0-power polynomial.
Parameters
 in c_coef Value of coefficient c
Returns
Number of roots
Definition at line 132 of file for_solve.c.
                               {
    assert(isfinite(c_coef));
    printf("E %g",c_coef);
    if (!compare(c_coef))
        return INFINITE;
    return 0;
}
References compare(), and INFINITE.
Referenced by Solve().
square_solve()
int square_solve (double a_coef, double b_coef, double c_coef, double * sol1, double * sol2)
Solver for square equations by coefficients.
Parameters
 in a_coef,b_coef,c_coef Value of coefficient a, b, c
 in *sol1,*sol2 Pointers to the answers' cells
Warning
a_coef != 0 (We assume that equation actually is Square)
Returns
Number of roots
Definition at line 78 of file for_solve.c.
{
    assert(isfinite(a_coef));
    assert(isfinite(b_coef));
    assert(isfinite(c_coef));
    assert(!compare(a_coef));
    assert(sol1 != NULL);
    assert(sol2 != NULL);
    assert(sol1 != sol2);
    double discr = 0; // The discriminant of equation and its square root
    double inv_a_coefx2 = 1/(a_coef*2); // Due to inevitability of computation we take it once
    discr = b_coef * b_coef - 4*a_coef*c_coef;// compute the discriminant of equation
    if (compare(discr)){
        *sol1 = -b_coef*inv_a_coefx2;
        *sol2 = *sol1;
        return 1;
    }
    else if (discr > 0){
        discr = sqrt(discr);
        *sol1 = (-b_coef + discr)*inv_a_coefx2;
        *sol2 = (-b_coef - discr)*inv_a_coefx2;
        return 2;
    }
    else{
        //Complex case
        return 0;
    }
}
References compare().
Referenced by Solve().