Comparing
Functions for comparing doubles and floats.
Functions
int compare (double dble)
Comparing double with 0.
int compare2 (double dble1, double dble2)
Comparing 2 doubles.
Variables
const double EPS = 0.00001
defines the accuracy of comparing
Detailed Description
Functions for comparing doubles and floats.
Function Documentation
compare()
int compare (double dble)
Comparing double with 0.
Parameters
 in dble
Returns
Result of comparing (True <==> (dble == 0))
Definition at line 300 of file for_solve.cpp.
                         {
    assert (isfinite(dble));
    return EPS > fabs (dble);
}
References EPS.
Referenced by linear_solve(), Solve(), special_case(), and square_solve().
compare2()
int compare2 (double dble1, double dble2)
Comparing 2 doubles.
Parameters
 in dble1,dble2 Doubles to compare
Returns
Result of comparing (True <==> (dble1 == dble2))
Definition at line 317 of file for_solve.cpp.
                                        {
    assert (isfinite (dble1));
    assert (isfinite (dble2));
    return EPS > fabs (dble1 - dble2);
}
References EPS.
Referenced by tester().
Variable Documentation
EPS
const double EPS = 0.00001
defines the accuracy of comparing
Definition at line 290 of file for_solve.cpp.
Referenced by compare(), and compare2().