Main_part
General functions of solving.
Modules
Comparing
Functions for comparing doubles and floats.
Functions
void input (double *a_coef, double *b_coef, double *c_coef)
Adjusts alternately input of 3 coefficients.
void get_input (double *coef, char letter)
Processing input of one variable.
int Solve (double a_coef, double b_coef, double c_coef, double *sol1, double *sol2)
Implementing branching between solving cases and unificating answers.
int square_solve (double a_coef, double b_coef, double c_coef, double *sol1, double *sol2)
Solver for square equations by coefficients.
int linear_solve (double b_coef, double c_coef, double *sol1)
Solver for linear equations by coefficients.
int special_case (double c_coef)
Solver for case of 0-power polynomial.
int output (double sol1, double sol2, int num_roots)
Adjusts onput of solutions.
Detailed Description
General functions of solving.
Function Documentation
get_input()
void get_input (double * coef, char letter)
Processing input of one variable.
Parameters
 in *coef Pointer for coefficient cell
 in letter Name of coef that will be printed
Definition at line 50 of file for_solve.cpp.
                                          {
    printf ("%c: ", letter);
    int flag;
    /*while ((flag = scanf ("%lf", coef)) == EOF || !flag){
        printf ("Your input has wrong type, please, reenter coefficient %c\n", letter);
        printf ("%c: ", letter);
        if (flag != EOF)
            while (getchar () != '\n') // buffer clean
                ;
    }*/
        while ((flag = getw (coef)) != 1){
        switch (flag){
            case 0: {
                printf ("Your input has wrong type, please, reenter coefficient %c\n", letter);
                printf ("%c: ", letter);
                break;
            }
            case 2: {
                printf ("Your input is too big, please, reenter coefficient %c\n", letter);
                printf ("%c: ", letter);
                break;
            default: printf ("Error: InputError");
            }
        }
        }
}
References getw().
Referenced by input().
input()
void input (double * a_coef, double * b_coef, double * c_coef)
Adjusts alternately input of 3 coefficients.
Parameters
 in *a_coef Pointer for coefficient a's cell
 in *b_coef Pointer for coefficient b's cell
 in *c_coef Pointer for coefficient c's cell
Definition at line 32 of file for_solve.cpp.
                                                          {
    printf ("Please, enter the coefficients of your equation of the form a*x^2 + b*x + c = 0\n");
    get_input (a_coef, 'a');
    get_input (b_coef, 'b');
    get_input (c_coef, 'c');
    //printf ("%lg %lg %lg", *a_coef, *b_coef, *c_coef);
}
References get_input().
Referenced by main().
linear_solve()
int linear_solve (double b_coef, double c_coef, double * sol1)
Solver for linear equations by coefficients.
Parameters
 in b_coef,c_coef Value of coefficient a, b, c
 in *sol1 Pointer to the answer's cell
Warning
b_coef != 0 (We assume that equation actually is Linear)
Returns
Number of roots
Definition at line 197 of file for_solve.cpp.
                                                              {
    assert (isfinite (b_coef));
    assert (isfinite (c_coef));
    assert (!compare (b_coef));
    assert (sol1 != NULL);
    *sol1 = -c_coef / b_coef;
    return 1;
}
References compare().
Referenced by Solve().
output()
int output (double sol1, double sol2, int num_roots)
Adjusts onput of solutions.
Use case branch by the number of roots
Parameters
 in sol1,sol2 Solutions to print
 in num_roots Number of roots
Returns
code-of-exit
Definition at line 241 of file for_solve.cpp.
                                                   {
    assert (isfinite (sol1));
    assert (isfinite (sol2));
    switch (num_roots){
    case 1 : {
        printf ("Your equation has only one root: %g", sol1);
        return 0;
    }
    case 2 : {
        printf ("Your equation has two roots: \nx1 = %g \nx2 = %g", sol1, sol2);
        return 0;
    }
    case 0 : {
        printf ("Your equation has no roots");
        return 0;
    }
    case INFINITE : {
        printf ("Your equation has INFINITE roots");
        return 0;
    }
    default : return 2;
    }
}
References INFINITE.
Referenced by main().
Solve()
int Solve (double a_coef, double b_coef, double c_coef, double * sol1, double * sol2)
Implementing branching between solving cases and unificating answers.
If equation has more or less than 2 roots, take it as a standart that sol1 = sol2
And if they are undefined (0 or INF) assign them 0-valued
Parameters
 in a_coef,b_coef,c_coef Value of coefficient a, b, c
 in *sol1,*sol2 Pointers to the answers' cells
Returns
Number of roots
Definition at line 99 of file for_solve.cpp.
                                                                                 {
    assert (isfinite (a_coef));
    assert (isfinite (b_coef));
    assert (isfinite (c_coef));
    assert (sol1 != NULL);
    assert (sol2 != NULL);
    assert (sol1 != sol2);
    int num_roots = TOXIC;
    if (compare (a_coef)) {
        if (compare (b_coef)){
            num_roots = special_case (c_coef);
            *sol1 = 0;
            *sol2 = *sol1;
        }
        else{
            num_roots = linear_solve (b_coef, c_coef, sol1);
            *sol2 = *sol1;
        }
    }
    else num_roots = square_solve (a_coef, b_coef, c_coef, sol1, sol2);
    return num_roots;
}
References compare(), linear_solve(), special_case(), square_solve(), and TOXIC.
Referenced by main(), and tester().
special_case()
int special_case (double c_coef)
Solver for case of 0-power polynomial.
Parameters
 in c_coef Value of coefficient c
Returns
Number of roots
Definition at line 219 of file for_solve.cpp.
                                {
    assert (isfinite (c_coef));
    if (compare(c_coef)) return INFINITE;
    return 0;
}
References compare(), and INFINITE.
Referenced by Solve().
square_solve()
int square_solve (double a_coef, double b_coef, double c_coef, double * sol1, double * sol2)
Solver for square equations by coefficients.
Parameters
 in a_coef,b_coef,c_coef Value of coefficient a, b, c
 in *sol1,*sol2 Pointers to the answers' cells
Warning
a_coef != 0 (We assume that equation actually is Square)
Returns
Number of roots
Definition at line 145 of file for_solve.cpp.
                                                                                         {
    assert (isfinite (a_coef));
    assert (isfinite (b_coef));
    assert (isfinite (c_coef));
    assert (!compare (a_coef));
    assert (sol1 != NULL);
    assert (sol2 != NULL);
    assert (sol1 != sol2);
    double discr = 0; // The discriminant of equation and its square root
    double inv_a_coefx2 = 1 / (a_coef * 2); // Due to inevitability of computation we take it once
    discr = b_coef * b_coef - 4 * a_coef * c_coef;// compute the discriminant of equation
    if (compare (discr)){
        *sol1 = -b_coef * inv_a_coefx2;
        *sol2 = *sol1;
        return 1;
    }
    else if (discr > 0){
        discr = sqrt (discr);
        *sol1 = (-b_coef + discr) * inv_a_coefx2;
        *sol2 = (-b_coef - discr) * inv_a_coefx2;
        return 2;
    }
    *sol1 = 0;
    *sol2 = *sol1;
    return 0;
}
References compare().
Referenced by Solve().